### ISSUE TITLE
Mache

### ISSUE THREAD

**Issue by Gladiator1337** [willis81808/Mache#1]
Hello, 

if I use Mache, the multiplayerunlimiter works fine but i cant use my Keyboard anymore for Chat or Worldname / Servername and the menu Bugs too.

Would it be possible change the Hotkey to custom one ? I cant use the debug console anymore cause its same Key F1

Best Regards

Gladiator1337

**Comment by DawnTroll** [comment]
I would also be for a custom keybind if possible.

**Comment by willis81808** [comment]
@Gladiator1337 Can you provide steps to reproduce the keyboard lock issue?

**Comment by Gladiator1337** [comment]
@willis81808 start to host a game name it and start to chat

**Comment by MacedonskyAlex** [comment]
You can't write messages in the chat

**Comment by willis81808** [comment]
Identified the issue as a problem with the UniverseLib config taken from their documentation. Resolved now in my testing
